package com.techie345.moneys.financial;
import java.util.*; import java.util.stream.*; import org.springframework.stereotype.Service; import com.techie345.moneys.financial.account.*; import com.techie345.moneys.financial.transaction.*; import com.techie345.moneys.financial.asset.*; import com.techie345.moneys.financial.holding.*; import com.techie345.moneys.financial.liability.*;
import static com.techie345.moneys.financial.CalculationReadModels.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
@Service @ConditionalOnProperty(name="app.database.enabled", havingValue="true", matchIfMissing=true) public class FinancialCalculationService {
 private final AccountRepository accounts; private final TransactionRepository transactions; private final AssetRepository assets; private final HoldingRepository holdings; private final LiabilityRepository liabilities;
 public FinancialCalculationService(AccountRepository a,TransactionRepository t,AssetRepository as,HoldingRepository h,LiabilityRepository l){accounts=a;transactions=t;assets=as;holdings=h;liabilities=l;}
 private List<TransactionEntity> tx(UUID o){return transactions.findAllByOwnerId(o);}
 public Overview overview(UUID o){List<TransactionEntity> t=tx(o);long income=t.stream().filter(x->x.getKind()==TransactionKind.INCOME).mapToLong(TransactionEntity::getAmountCents).sum();long spending=t.stream().filter(x->x.getKind()==TransactionKind.SPENDING||x.getKind()==TransactionKind.REFUND).mapToLong(x->x.getKind()==TransactionKind.REFUND?-x.getAmountCents():x.getAmountCents()).sum();return new Overview(income,spending,netWorth(o),income==0?0:(double)(income-spending)/income);}
 public Spending spending(UUID o){Map<String,Long> by=tx(o).stream().filter(x->x.getKind()==TransactionKind.SPENDING||x.getKind()==TransactionKind.REFUND).collect(Collectors.groupingBy(TransactionEntity::getCategory,Collectors.summingLong(x->x.getKind()==TransactionKind.REFUND?-x.getAmountCents():x.getAmountCents())));return new Spending(by.values().stream().mapToLong(Long::longValue).sum(),by);}
 public Income income(UUID o){Map<String,Long> by=tx(o).stream().filter(x->x.getKind()==TransactionKind.INCOME).collect(Collectors.groupingBy(TransactionEntity::getCategory,Collectors.summingLong(TransactionEntity::getAmountCents)));return new Income(by.values().stream().mapToLong(Long::longValue).sum(),by);}
 public Investing investing(UUID o){return new Investing(holdings.findAllByOwnerId(o).stream().mapToLong(HoldingEntity::getMarketValueCents).sum(),tx(o).stream().filter(x->x.getKind()==TransactionKind.INVESTMENT).mapToLong(TransactionEntity::getAmountCents).sum());}
 public long netWorth(UUID o){var ownerAccounts=accounts.findAllByOwnerId(o);var ownerLiabilities=liabilities.findAllByOwnerId(o);var ownerHoldings=holdings.findAllByOwnerId(o);var holdingAccounts=ownerHoldings.stream().map(HoldingEntity::getAccountId).collect(Collectors.toSet());long cash=ownerAccounts.stream().filter(x->x.getKind()==AccountKind.CASH).mapToLong(AccountEntity::getBalanceCents).sum();long investments=ownerHoldings.stream().mapToLong(HoldingEntity::getMarketValueCents).sum()+ownerAccounts.stream().filter(x->x.getKind()==AccountKind.INVESTMENT).filter(x->!holdingAccounts.contains(x.getId())).mapToLong(AccountEntity::getBalanceCents).sum();long debtAccounts=ownerAccounts.stream().filter(x->x.getKind()==AccountKind.CREDIT||x.getKind()==AccountKind.LOAN).mapToLong(x->Math.abs(x.getBalanceCents())).sum();long debt=debtAccounts+ownerLiabilities.stream().filter(l->ownerAccounts.stream().noneMatch(a->liabilityMatchesAccount(l,a))).mapToLong(LiabilityEntity::getBalanceCents).sum();return cash+investments+assets.findAllByOwnerId(o).stream().mapToLong(AssetEntity::getValueCents).sum()-debt;}
 private boolean liabilityMatchesAccount(LiabilityEntity l,AccountEntity a){if(l.getAccountId()!=null)return l.getAccountId().equals(a.getId());if(l.getKind()==LiabilityKind.CREDIT_CARD&&a.getKind()!=AccountKind.CREDIT)return false;if(l.getKind()!=LiabilityKind.CREDIT_CARD&&a.getKind()!=AccountKind.LOAN)return false;Set<String> ignored=Set.of("account","card","cash","back","bank","home","loan","the","and","for","it");Set<String> accountWords=words(a.getInstitution(),ignored);accountWords.addAll(words(a.getName(),ignored));return words(l.getName(),ignored).stream().anyMatch(accountWords::contains);}
 private Set<String> words(String value,Set<String> ignored){Set<String> result=new HashSet<>();for(String word:value.toLowerCase().split("\\W+"))if(word.length()>2&&!ignored.contains(word))result.add(word);return result;}
}
